include ../../../config/makeconfig

OBJ = \

OBJ := \
$(OBJ) \
general_op1e.o \
general_ecore.o \
general_meanfield.o \
general_hprod_kinetic.o \
general_hprod_kinetic_2d.o \
general_hprod_kinetic_fft.o \
general_hprod_potential.o \
general_hprod_corefield.o \
general_hprod_proj.o \
general_hprod_op1e.o \
general_exp_kinetic_fft.o \
general_full_kinetic.o \
general_diff.o \
general_diff_2d.o \
general_ovlp.o \
general_ovlp1.o \
general_d1wfn.o \
general_print_ovlp.o \
general_symm.o \
general_lanczos.o \
general_hprod1.o 

OBJ := \
$(OBJ) \
general_hwfn_kinetic.o \
general_hwfn_kinetic_fft.o \
general_hwfn_potential.o \
general_hwfn_jk.o \
general_hwfn_weff.o \
general_hwfn_zaxpy.o \
general_int1e.o \
general_int2e.o \
general_rotmo.o \

include $(TD1D_CON)/make.objcomp
