include ../../config/makeconfig

OBJ = \
util_itochar.o \
util_transchar.o \
util_clock.o \
util_det.o \
util_svd_real.o \
util_svd_comp.o \
util_diag_real.o \
util_diag_comp.o \
util_diag_ovlp_real.o \
util_diag_ovlp_comp.o \
util_matinv.o \
util_gmatinv.o \
util_matinv_reg.o \
util_hlineq_reg.o \
util_reg_mat.o \
util_norm2e.o \
util_proj.o \
util_trimat.o \
util_usymu.o \
util_asyma.o \
util_takagi.o \
util_youla.o \
util_powmat.o \
util_syseq_real.o \
util_ifact.o \
util_bicoeff.o \
util_gdiag_comp.o \
util_adiag_comp.o \
util_index_double.o \
util_hermc.o \
util_window.o \
util_lineq.o \
util_matoutc.o \
util_sqrth.o \
util_expihd.o \
util_gexphd.o \
util_gexpihd.o \
util_exp_asym.o \
util_krylov.o \
#util_fft.o \
#util_fft2d.o \

OBJ := $(OBJ) \
util_blas.o \
util_gather.o \
util_maxloc.o \

include $(TD1D_CON)/make.objcomp
