include ../../../config/makeconfig

########## public ##########
# serial
OBJ = \
hf_clear.o \
hf_size.o \
hf_print.o \
hf_read.o \
hf_readhf.o \
hf_wfn2e.o \
hf_den2e.o \
hf_write.o \
hf_write_orb.o \
hf_hprod.o \
hf_v2prod.o \
hf_hprod_gbasis.o \
hf_op1e.o \
hf_domask.o \
hf_capped.o \
hf_iprod.o \
hf_ort.o \
hf_norm.o \
hf_exp_potential.o \
hf_n2err.o \
hf_fulldiag.o \
hf_print_eig.o \
hf_print_ovlp.o \
hf_print_op1e.o \
hf_print_rho1.o \
hf_print_gvb.o \
hf_print_vlocal.o \
hf_pospot1.o \
mp_gsmp2.o \
mp_moeri.o

########## private ##########
# serial
OBJ := $(OBJ) \
hf_hprod_meanfield.o \
hf_hprod_meanfield_def.o \
hf_hprod_meanfield_nosi.o \
hf_hprod_meanfield_nosi_small.o \
hf_hprod_sum.o \
hf_hprod_proj.o \
hf_enec.o \
hf_ene2.o \
hf_ovdef.o \
hf_ovlp.o \
hf_ovlp1.o \
hf_setfroz.o \
hf_full_kinetic.o \
hf_full_potential.o \
hf_full_diag.o \
hf_full_meanfield.o \


include $(TD1D_CON)/make.objcomp
