include ../../config/makeconfig

OBJ = \
guess.o \
guess_read.o \
guess_hf.o \
guess_no.o \
guess_cas.o \
guess_apsg.o \
guess_x2e.o \
guess_lcao.o \
guess_core.o \
guess_order.o \
guess_read_gbasis.o \

include $(TD1D_CON)/make.objcomp
