include ../../../config/makeconfig

OBJ = \
x2e_clear.o \
x2e_size.o \
x2e_print.o \
x2e_readhf.o \
x2e_read.o \
x2e_wfn2e.o \
x2e_den2e.o \
x2e_write.o \
x2e_hprod.o \
x2e_op1e.o \
x2e_domask.o \
x2e_capped.o \
x2e_iprod.o \
x2e_ort.o \
x2e_norm.o \
x2e_exp_kinetic_fft.o \
x2e_exp_potential.o \
x2e_n2err.o \
x2e_dyson.o \

OBJ := $(OBJ) \
x2e_hprod_kinetic.o \
x2e_hprod_kinetic_fft.o \
x2e_hprod_potential.o \
x2e_ene.o \
x2e_ovlp.o \
x2e_printno.o \

include $(TD1D_CON)/make.objcomp
