include ../../config/makeconfig

OBJ = \
const_mod.o \
fft_mod.o \
grid_mod.o \
init_mod.o \
mol_mod.o \
omp_mod.o \
field_mod.o \
prop_mod.o \
root_mod.o \
thresh_mod.o \
wfn_mod.o \
io_mod.o \
cc_mod.o \

include $(TD1D_CON)/make.objcomp
