include ../../config/makeconfig

OBJ = \
tdse.o \
tdse_cycle.o \
tdse_cycle_u1prop.o \
tdse_cycle_u2prop.o \
tdse_cycle_arnoldi.o \
tdse_cycle_cstep.o \
tdse_cycle_vstep.o \
tdse_cycle_astep.o \
tdse_print.o \
tdse_print_2e.o \
tdse_summary.o \
tdse_dump.o \
#tdse_printpt.o

include $(TD1D_CON)/make.objcomp
