include ../../config/makeconfig

OBJ = \
grid_init.o \
grid_final.o \
grid_alloc.o \
grid_dealloc.o \
grid_efree.o \
grid_mkgrid.o \
grid_fdcoeff1.o \
grid_fdcoeff2.o \
grid_mkmask.o \
grid_print.o \
grid_v1.o \
grid_v2.o \
grid_irmax.o \
grid_f12.o \
grid_mkinner.o \
gbasis_init.o \
gbasis_final.o

include $(TD1D_CON)/make.objcomp
