include ../../config/makeconfig

OBJ = \
prop.o \
prop_exp.o \
prop_rk4.o \
prop_v2rk4.o \
prop_vrk5.o \
prop_v2vrk5.o \
prop_euler.o \
prop_split_exp.o \
prop_split_rk4.o \
prop_split_vrk5.o \
prop_abm.o \

include $(TD1D_CON)/make.objcomp
