include ../../config/makeconfig

OBJ = \
field.o \
efield.o \
efield_trape.o \
efield_sin2.o \
efield_flat.o \
efield_pulse.o \
afield.o \
afield_trape.o \
afield_sin2.o \
afield_flat.o \
int_field.o \
int_field_trape.o \
int_field_sin2.o \
int_field_flat.o

include $(TD1D_CON)/make.objcomp
