include ../../config/makeconfig

OBJ = \
init.o \
initpt.o \
init_summary.o \
init_cycle.o \
init_cycle_fulld.o \
init_cycle_ahprop.o \
init_cycle_aughess.o \
init_cycle_aughess_prop.o \
init_cycle_diag.o \
init_cycle_prop1.o \
init_cycle_prop1.o \
init_cycle_prop2.o \
init_cycle_prop3.o \
init_cycle_propcipq.o \
init_cycle_diagp_propq.o \
init_cycle_diag_oo_vo.o \
init_cycle_diagprop.o \
init_cycle_diagpropgbt.o \
init_cycle_diagcipq.o \
init_cycle_propcip2p1q.o \
init_cycle_diagcip2p1q.o \
init_cycle_prop1gbt.o \
#init_cycle_proppropgbt.o \
#init_cycle_proppropprop.o \

include $(TD1D_CON)/make.objcomp
